#properties for the local environment
 
api:
  id: "123456" 
   
#Http Listener Configuration
http:
  port: "8081" 

#kafka configuration
  
kafka:
  server : "server"
  partition: "partition"
  topic: "topicname"
  key : "1234"
