#properties for the DEV1 environment
  
api:
  id: "123456"    
  
#Http Listener Configuration
http:
  port: "8081" 
  request:
    protocol: "HTTP"
    host: "localhost"
    port: "8091"
    path: "/" 
  
#Microsoft dynamics 365 configuration
config-oauth-user-pass:
  username: placeholder
  password: placeholder
  resource: placeholder
  clientId: placeholder
  clientSecret: placeholder
  tokenRequestEndpoint: placeholder